/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TicTacToeModel */

#ifndef _Included_TicTacToeModel
#define _Included_TicTacToeModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TicTacToeModel
 * Method:    getLENGTH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_TicTacToeModel_getLENGTH
        (JNIEnv *, jobject);

/*
 * Class:     TicTacToeModel
 * Method:    initializeBoard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TicTacToeModel_initializeBoard
        (JNIEnv *, jobject);

/*
 * Class:     TicTacToeModel
 * Method:    getCell
 * Signature: (II)C
 */
JNIEXPORT jchar JNICALL Java_TicTacToeModel_getCell
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     TicTacToeModel
 * Method:    makeMove
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_TicTacToeModel_makeMove
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     TicTacToeModel
 * Method:    checkWin
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_TicTacToeModel_checkWin
        (JNIEnv *, jobject);

/*
 * Class:     TicTacToeModel
 * Method:    isXTurn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_TicTacToeModel_isXTurn
        (JNIEnv *, jobject);

/*
 * Class:     TicTacToeModel
 * Method:    checkForDraw
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_TicTacToeModel_checkForDraw
        (JNIEnv *, jobject);

/*
 * Class:     TicTacToeModel
 * Method:    resetBoard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TicTacToeModel_resetBoard
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
